# Generated by Django 5.2.9 on 2026-02-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_evaluation_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("employee", "Employee"), ("manager", "Manager")],
                default="employee",
                max_length=20,
            ),
        ),
    ]
