# Generated by Django 5.2.9 on 2026-02-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_evaluation_final_score_task_importance_degree_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="importance_degree",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "High"), (2, "Medium"), (3, "Low")], default=1
            ),
        ),
    ]
